### ISSUE TITLE
Plugin doesn´t load | BungeeCord 1.9.4

### ISSUE THREAD

**Issue by PlaysideGit** [vincidev/BungeeBan#17]
I´m using BungeeBan (v. 2.6.4), but it doesn´t load! At loading screen comes this error:
`22:16:24 [WARNING] Error enabling plugin BungeeBan
java.lang.UnsupportedClassVersionError: de/vincidev/bungeeban/BungeeBan : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:258)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

Hope you can help me/of fix it.

Thanks!

**Comment by vincidev** [comment]
Which version of java are you using?

**Comment by PlaysideGit** [comment]
Java 7
Can you tell me, how i can upgrade to Java 8?
PS: I have a Debian 8 Server with SSH

Thanks!

**Comment by ImNatho** [comment]
Try this [link](http://lmgtfy.com/?q=Debian+8+upgrade+to+java+8+jre)

**Comment by vincidev** [comment]
The plugin should also be available with java 7 though, as so many people use it. Next version will also work with java 7
